title: Abner Kallil
description: Contabilidade, Ciência de Dados, Tecnologia e estudos.
lang: pt-BR

theme: minima

author:
  name: Abner Kallil
  email: abner_kallil@hotmail.com

github_username: abnerkallil

show_excerpts: true

header_pages:
  - sobre.md
