title: Uma Xicara de Café
description: Contabilidade, Ciência de Dados, Tecnologia e estudos.
lang: pt-BR

theme: minima

author: Abner Coimbra
email: abner_kallil@hotmail.com

github_username: abnerkallil

show_excerpts: true

header_pages:
  - sobre.md
